version: '3'
services:
  react-ui:
    build:
      context: ./my-app
    ports:
      - "3000:3000"
    container_name: react-ui
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules